### ISSUE TITLE
Shared `X25519_PRIVATE_KEY` for Development

### ISSUE THREAD

**Issue by EresDev** [EresDevOrg/ubiquibot-issues#10]
Can somebody work on generating a new `X25519_PRIVATE_KEY` for the ubiquibot organization? We need to share it for development purposes.

1. Generate a new key
2. Encrypt a new `evmPrivateKeyEncrypted` (no funds!) and add to the org bot config
3. Add the shared test key to the `comment-incentives` readme.

**Comment by web4er** [comment]
i think we need to update a bit the readme

**Comment by EresDev** [comment]
Link below for conversation context. It was to me. Anyways you need to create a new private key for this task!

**Comment by web4er** [comment]
##### Update
I just changed it to `627H-BcWbcp_O3YmQGIA6MqA9DK3iC7GQ`

I hope that it doesn't break production for some reason (it should get it from Netlify secrets, but not sure if we implemented this correctly!)

I fear that we might need to build a feature for this to support development key pair and production. Unfortunately I'm already winding down for the day so I'll leave you guys to try and investigate.

**Comment by EresDev** [comment]
changing openai key

**Comment by EresDev** [comment]
Let's see

**Comment by EresDev** [comment]
Let's see 3

**Comment by EresDev** [comment]
post-review-1

**Comment by EresDev** [comment]
post-rewiew-2
invalid openai key

**Comment by EresDev** [comment]
post-preview-3
valid openai key and fixed relevances 1

**Comment by EresDev** [comment]
1

**Comment by EresDev** [comment]
1

**Comment by EresDev** [comment]
1

**Comment by EresDev** [comment]
1

**Comment by EresDev** [comment]
test-1

**Comment by EresDev** [comment]
test 2

**Comment by EresDev** [comment]
test 3

**Comment by EresDev** [comment]
before new changes

**Comment by EresDev** [comment]
after recent changes
