### ISSUE TITLE
Post comment with summary and details to GitHub issue

### ISSUE THREAD

**Issue by EresDev** [EresDevOrg/ubiquibot-issues#15]
In the v1 of the Ubiquibot, when a result gets evaluated, a recap is posted to the related issue with a summary and details of the rewards as well as the link to the rewards themselves.

The same logic should be applied in the v2 version by creating a new Module responsible to post that comment. This module will receive a similar input than the one mentioned

The module should be:
- possible to enable / disable
- eventually configurable (what data to show / hide)
- coming with tests

**Comment by web4er** [comment]
how we can deal with comment outputs. Perhaps we can have a standard recognized property on the output interface? Then the kernel can decide whether to pass it around or something. 

```ts
interface PluginOutput {
  comment: string; // html comment
  rewards: Rewards; // { "whilefoo": "500", "token": "0x0" } etc
}
```

**Comment by EresDev** [comment]
To me 1 is the most straightforward to do for few reasons:
- the comment reward plugin has all the needed data already
- it can import the https://github.com/ubiquibot/permit-generation to generate permits itself
- if it is done this way it can be used as a complete standalone without the kernel

3 might make more sense in terms of architecture however. In such case the kernel should pass down results. It is more of an architecture question. Although, if we ever have other plugins in the flow that have influence on the total incentives, it would make sense to go through the kernel to aggregate the total result.

**Comment by EresDev** [comment]
Let's see

**Comment by EresDev** [comment]
After deleting local config file

**Comment by EresDev** [comment]
fixing config of private repo

**Comment by EresDev** [comment]
adding local config back

**Comment by EresDev** [comment]
added ubq-bot to new conversation-reward repo

**Comment by EresDev** [comment]
Remove fixed relevance for PR comments

**Comment by EresDev** [comment]
Remove fixed relevance for PR comments from local config

**Comment by EresDev** [comment]
let's see again

**Comment by EresDev** [comment]
once more

**Comment by EresDev** [comment]
### Test

should evaluate PR comments with code mentions or code suggestions using OpenAI. 

####  PASSED

**Comment by EresDev** [comment]
post review

**Comment by EresDev** [comment]
post token limit increase

**Comment by EresDev** [comment]
after removing issue specifications from code review evaluation  prompt

**Comment by EresDev** [comment]
After prompt update to cover all PR comments

**Comment by EresDev** [comment]
After merge

**Comment by EresDev** [comment]
after camel case fix
